# Generated by Django 5.2.6 on 2025-09-13 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.SmallIntegerField(choices=[(1, '1 Semester'), (2, '2 Semester'), (3, '3 Semester'), (4, '4 Semester'), (5, '5 Semester'), (6, '6 Semester')])),
                ('cia', models.SmallIntegerField(choices=[(1, 'C.I.A - I'), (2, 'C.I.A - I'), (3, 'C.I.A - III')])),
                ('mark', models.SmallIntegerField()),
                ('assignment', models.BooleanField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app.student')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subj', to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.SmallIntegerField(choices=[(1, '1 Semester'), (2, '2 Semester'), (3, '3 Semester'), (4, '4 Semester'), (5, '5 Semester'), (6, '6 Semester')])),
                ('internal', models.SmallIntegerField()),
                ('external', models.SmallIntegerField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud', to='app.student')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='app.subject')),
            ],
        ),
    ]
