# Generated by Django 5.2.6 on 2025-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cia_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='part',
            field=models.SmallIntegerField(choices=[(1, 'Part 1'), (2, 'Part 2'), (3, 'Part 3'), (4, 'Part 4'), (5, 'Part 5')], default=1),
        ),
    ]
